POST https://yacht-tracker-production.up.railway.app/api/scores
Content-Type: application/json

{
  "score": "30",
  "category": "Little Straight",
  "roll": "1 2 3 4 5"
}

###

POST http://localhost:8080/api/scores
#POST https://yacht-tracker-production.up.railway.app/api/scores
Content-Type: application/json

{
  "score": "3",
  "category": "ONES",
  "roll": "1 1 3 1 5"
}

###

POST http://localhost:8080/api/scores
Content-Type: application/json

{
  "score": "5",
  "category": "ONES",
  "roll": "1 1 1 1 1"
}

###

GET http://localhost:8080/api/averages?scoreCategory=ONES

###

DELETE https://yacht-tracker-production.up.railway.app/api/gameresults

###

DELETE http://localhost:8080/api/scores

###
